# Change these first
owner: Nevada-Esports-Education-League
repo: status
assignees:
  - upptime-bot
  - NVEsportsEducationLeague

sites:
  - name: Website
    url: https://www.nvesportseducationleague.org/
  - name: Minecraft Server
    url: play.nvesportseducationleague.org
    port: 25565
    check: "tcp-ping"
    ipv6: false
  - name: Authentik 
    url: https://authentik.nvesportseducationleague.org
  - name: Bluemap
    url: https://bluemap.nvesportseducationleague.org
  - name: Docuseal
    url: https://docuseal.nvesportseducationleague.org
  - name: Element
    url: https://element.nvesportseducationleague.org
  - name: OpenAudioMC
    url: https://endpoint.nvesportseducationleague.org
  - name: Pelican
    url: https://pelican.nvesportseducationleague.org
  - name: Shelf
    url: https://shelf.nvesportseducationleague.org
  - name: Vault
    url: https://vault.nvesportseducationleague.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nvesportseducationleague.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Nevada-Esports-Education-League/status/master/assets/neel.png
  name: NEEL Status Page
  introTitle: "Are NEEL's services down?"
  introMessage: "This is a status page of NEEL's services hosted on GitHub"
  theme: ocean
  favicon: https://raw.githubusercontent.com/Nevada-Esports-Education-League/status/master/assets/favicon-32x32.png
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://www.nvesportseducationleague.org/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
