# Change these first
owner: Nevada-Esports-Education-League
repo: status
assignees:
  - NoteStars

sites:
  - name: Website
    url: https://www.nvesportseducationleague.org/
  - name: Authentik 
    url: https://authentik.nvesportseducationleague.org
  - name: Pelican
    url: https://pelican.nvesportseducationleague.org
  - name: OpenAudioMC
    url: https://endpoint.nvesportseducationleague.org
  - name: Minecraft Server
    url: play.nvesportseducationleague.org
    port: 25565
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: nvesportseducationleague.org
  # baseUrl: /your-repo-name
  logoUrl: 
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "This is a status page of NEEL's website and services hosted on GitHub"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
